name: Deploy to Tomcat
 
on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: [self-hosted, windows]  # Use your self-hosted Windows runner
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      #- name: Set up JDK
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '21'  # Use the version that matches your project
      #    distribution: 'oraclejdk'
    

      - name: Verify Maven Installation
        run: C:\maven\bin\mvn -version
          
      - name: Build with Maven
        shell: cmd
        run: C:\maven\bin\mvn -f C:\actions-runner\_work\security\security clean package

      - name: List target directory
        run: dir target
        working-directory: ./
        
      - name: Deploy to Tomcat
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
          TOMCAT_PORT: ${{ secrets.TOMCAT_PORT }}
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }}
        run: |
          & "C:\Windows\System32\curl.exe" -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASS }}" `
               -T target/security.war `
               "http://${{ secrets.TOMCAT_HOST }}:${{ secrets.TOMCAT_PORT }}/manager/text/deploy?path=/security&update=true"
