name: Deploy to Tomcat

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: [self-hosted, windows]  # Use your self-hosted Windows runner
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Install Maven
        run: |
          $mavenUrl = "https://archive.apache.org/dist/maven/maven-3/3.8.5/binaries/apache-maven-3.8.5-bin.zip"
          $mavenZip = "apache-maven-3.8.5-bin.zip"
          $mavenDir = "C:\maven"
          Invoke-WebRequest -Uri $mavenUrl -OutFile $mavenZip
          Expand-Archive -Path $mavenZip -DestinationPath $mavenDir
          echo "M2_HOME=$mavenDir\apache-maven-3.8.5" >> $GITHUB_ENV
          echo "PATH=$mavenDir\apache-maven-3.8.5\bin;$env:PATH" >> $GITHUB_ENV

          
      #- name: Set up JDK
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '21'  # Use the version that matches your project
      #    distribution: 'oraclejdk'

      - name: Build with Maven
        run: mvn clean package
        env:
          JAVA_HOME: ${{ env.JAVA_HOME }}
          M2_HOME: ${{ env.M2_HOME }}
          PATH: ${{ env.M2_HOME }}\bin;${{ env.PATH }}
          
      - name: Deploy to Tomcat
        env:
          TOMCAT_USER: ${{ secrets.TOMCAT_USER }}
          TOMCAT_HOST: ${{ secrets.TOMCAT_HOST }}
          TOMCAT_PORT: ${{ secrets.TOMCAT_PORT }}
          TOMCAT_PASS: ${{ secrets.TOMCAT_PASS }}
        run: |
          curl -u $TOMCAT_USER:$TOMCAT_PASS \
               -T target/security.war \
               "http://$TOMCAT_HOST:$TOMCAT_PORT/manager/text/deploy?path=/security&update=true"
